// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from 'D:/leetcode/wang-react-hooks/docs/guide.md?type=frontmatter';
import { demoIndex as dmi0 } from 'D:/leetcode/wang-react-hooks/docs/guide.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from 'D:/leetcode/wang-react-hooks/docs/index.md?type=frontmatter';
import { demoIndex as dmi1 } from 'D:/leetcode/wang-react-hooks/docs/index.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/Demo1/index.md?type=frontmatter';
import { demoIndex as dmi2 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/Demo1/index.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useToggle/index.md?type=frontmatter';
import { demoIndex as dmi3 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useToggle/index.md?type=demo-index';

export const filesMeta = {
  'docs/guide': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/leetcode/wang-react-hooks/docs/guide.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/leetcode/wang-react-hooks/docs/index.md?type=text'),
  },
  'components/Demo1/index': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'D:/leetcode/wang-react-hooks/packages/hooks/src/Demo1/index.md?type=text'),
  },
  'components/useToggle/index': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'D:/leetcode/wang-react-hooks/packages/hooks/src/useToggle/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
