// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/guide":{"path":"guide","id":"docs/guide","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"components/Demo1/index":{"id":"components/Demo1/index","path":"components/demo1","parentId":"DocLayout","meta":{"_atom_route":true}},"components/useToggle/index":{"id":"components/useToggle/index","path":"components/use-toggle","parentId":"DocLayout","meta":{"_atom_route":true}},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout","prerender":false}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'D:/leetcode/wang-react-hooks/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.9_@types+node@22.13.4_eslint@8.57.1_jest@29.7.0_prettier@2.8.8_r_nxgnf5gijeyqutixz4boamzc5m/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp-production__dumi__theme__ContextWrapper" */'D:/leetcode/wang-react-hooks/.dumi/tmp-production/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'D:/leetcode/wang-react-hooks/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.9_@types+node@22.13.4_eslint@8.57.1_jest@29.7.0_prettier@2.8.8_r_nxgnf5gijeyqutixz4boamzc5m/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/guide': React.lazy(() => import(/* webpackChunkName: "docs__guide.md" */'D:/leetcode/wang-react-hooks/docs/guide.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'D:/leetcode/wang-react-hooks/docs/index.md')),
'components/Demo1/index': React.lazy(() => import(/* webpackChunkName: "packages__hooks__src__Demo1__index.md" */'D:/leetcode/wang-react-hooks/packages/hooks/src/Demo1/index.md')),
'components/useToggle/index': React.lazy(() => import(/* webpackChunkName: "packages__hooks__src__useToggle__index.md" */'D:/leetcode/wang-react-hooks/packages/hooks/src/useToggle/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'D:/leetcode/wang-react-hooks/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.9_@types+node@22.13.4_eslint@8.57.1_jest@29.7.0_prettier@2.8.8_r_nxgnf5gijeyqutixz4boamzc5m/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
