// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from 'D:/leetcode/wang-react-hooks/docs/guide.md?type=frontmatter';
import { demoIndex as dmi0 } from 'D:/leetcode/wang-react-hooks/docs/guide.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from 'D:/leetcode/wang-react-hooks/docs/index.md?type=frontmatter';
import { demoIndex as dmi1 } from 'D:/leetcode/wang-react-hooks/docs/index.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useBoolean/index.md?type=frontmatter';
import { demoIndex as dmi2 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useBoolean/index.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useCookieState/index.md?type=frontmatter';
import { demoIndex as dmi3 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useCookieState/index.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useDebounce/index.md?type=frontmatter';
import { demoIndex as dmi4 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useDebounce/index.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useDebounceFn/index.md?type=frontmatter';
import { demoIndex as dmi5 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useDebounceFn/index.md?type=demo-index';
import { frontmatter as fm6, toc as t6 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useGetState/index.md?type=frontmatter';
import { demoIndex as dmi6 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useGetState/index.md?type=demo-index';
import { frontmatter as fm7, toc as t7 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useLatest/index.md?type=frontmatter';
import { demoIndex as dmi7 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useLatest/index.md?type=demo-index';
import { frontmatter as fm8, toc as t8 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useLocalStorageState/index.md?type=frontmatter';
import { demoIndex as dmi8 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useLocalStorageState/index.md?type=demo-index';
import { frontmatter as fm9, toc as t9 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useMap/index.md?type=frontmatter';
import { demoIndex as dmi9 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useMap/index.md?type=demo-index';
import { frontmatter as fm10, toc as t10 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useMemoizedFn/index.md?type=frontmatter';
import { demoIndex as dmi10 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useMemoizedFn/index.md?type=demo-index';
import { frontmatter as fm11, toc as t11 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/usePrevious/index.md?type=frontmatter';
import { demoIndex as dmi11 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/usePrevious/index.md?type=demo-index';
import { frontmatter as fm12, toc as t12 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useResetState/index.md?type=frontmatter';
import { demoIndex as dmi12 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useResetState/index.md?type=demo-index';
import { frontmatter as fm13, toc as t13 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useSafeState/index.md?type=frontmatter';
import { demoIndex as dmi13 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useSafeState/index.md?type=demo-index';
import { frontmatter as fm14, toc as t14 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useSessionStorageState/index.md?type=frontmatter';
import { demoIndex as dmi14 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useSessionStorageState/index.md?type=demo-index';
import { frontmatter as fm15, toc as t15 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useSet/index.md?type=frontmatter';
import { demoIndex as dmi15 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useSet/index.md?type=demo-index';
import { frontmatter as fm16, toc as t16 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useSetState/index.md?type=frontmatter';
import { demoIndex as dmi16 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useSetState/index.md?type=demo-index';
import { frontmatter as fm17, toc as t17 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useThrottleFn/index.md?type=frontmatter';
import { demoIndex as dmi17 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useThrottleFn/index.md?type=demo-index';
import { frontmatter as fm18, toc as t18 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useToggle/index.md?type=frontmatter';
import { demoIndex as dmi18 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useToggle/index.md?type=demo-index';
import { frontmatter as fm19, toc as t19 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useUnmount/index.md?type=frontmatter';
import { demoIndex as dmi19 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useUnmount/index.md?type=demo-index';
import { frontmatter as fm20, toc as t20 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useUnmountedRef/index.md?type=frontmatter';
import { demoIndex as dmi20 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useUnmountedRef/index.md?type=demo-index';
import { frontmatter as fm21, toc as t21 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useUpdateEffect/index.md?type=frontmatter';
import { demoIndex as dmi21 } from 'D:/leetcode/wang-react-hooks/packages/hooks/src/useUpdateEffect/index.md?type=demo-index';

export const filesMeta = {
  'docs/guide': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/leetcode/wang-react-hooks/docs/guide.md?type=text'),
  },
  'docs/index': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/leetcode/wang-react-hooks/docs/index.md?type=text'),
  },
  'components/useBoolean/index': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'D:/leetcode/wang-react-hooks/packages/hooks/src/useBoolean/index.md?type=text'),
  },
  'components/useCookieState/index': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'D:/leetcode/wang-react-hooks/packages/hooks/src/useCookieState/index.md?type=text'),
  },
  'components/useDebounce/index': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'D:/leetcode/wang-react-hooks/packages/hooks/src/useDebounce/index.md?type=text'),
  },
  'components/useDebounceFn/index': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'D:/leetcode/wang-react-hooks/packages/hooks/src/useDebounceFn/index.md?type=text'),
  },
  'components/useGetState/index': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'D:/leetcode/wang-react-hooks/packages/hooks/src/useGetState/index.md?type=text'),
  },
  'components/useLatest/index': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'D:/leetcode/wang-react-hooks/packages/hooks/src/useLatest/index.md?type=text'),
  },
  'components/useLocalStorageState/index': {
    frontmatter: fm8,
    toc: t8,
    demoIndex: dmi8,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'D:/leetcode/wang-react-hooks/packages/hooks/src/useLocalStorageState/index.md?type=text'),
  },
  'components/useMap/index': {
    frontmatter: fm9,
    toc: t9,
    demoIndex: dmi9,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'D:/leetcode/wang-react-hooks/packages/hooks/src/useMap/index.md?type=text'),
  },
  'components/useMemoizedFn/index': {
    frontmatter: fm10,
    toc: t10,
    demoIndex: dmi10,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'D:/leetcode/wang-react-hooks/packages/hooks/src/useMemoizedFn/index.md?type=text'),
  },
  'components/usePrevious/index': {
    frontmatter: fm11,
    toc: t11,
    demoIndex: dmi11,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'D:/leetcode/wang-react-hooks/packages/hooks/src/usePrevious/index.md?type=text'),
  },
  'components/useResetState/index': {
    frontmatter: fm12,
    toc: t12,
    demoIndex: dmi12,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'D:/leetcode/wang-react-hooks/packages/hooks/src/useResetState/index.md?type=text'),
  },
  'components/useSafeState/index': {
    frontmatter: fm13,
    toc: t13,
    demoIndex: dmi13,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'D:/leetcode/wang-react-hooks/packages/hooks/src/useSafeState/index.md?type=text'),
  },
  'components/useSessionStorageState/index': {
    frontmatter: fm14,
    toc: t14,
    demoIndex: dmi14,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'D:/leetcode/wang-react-hooks/packages/hooks/src/useSessionStorageState/index.md?type=text'),
  },
  'components/useSet/index': {
    frontmatter: fm15,
    toc: t15,
    demoIndex: dmi15,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'D:/leetcode/wang-react-hooks/packages/hooks/src/useSet/index.md?type=text'),
  },
  'components/useSetState/index': {
    frontmatter: fm16,
    toc: t16,
    demoIndex: dmi16,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'D:/leetcode/wang-react-hooks/packages/hooks/src/useSetState/index.md?type=text'),
  },
  'components/useThrottleFn/index': {
    frontmatter: fm17,
    toc: t17,
    demoIndex: dmi17,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'D:/leetcode/wang-react-hooks/packages/hooks/src/useThrottleFn/index.md?type=text'),
  },
  'components/useToggle/index': {
    frontmatter: fm18,
    toc: t18,
    demoIndex: dmi18,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'D:/leetcode/wang-react-hooks/packages/hooks/src/useToggle/index.md?type=text'),
  },
  'components/useUnmount/index': {
    frontmatter: fm19,
    toc: t19,
    demoIndex: dmi19,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'D:/leetcode/wang-react-hooks/packages/hooks/src/useUnmount/index.md?type=text'),
  },
  'components/useUnmountedRef/index': {
    frontmatter: fm20,
    toc: t20,
    demoIndex: dmi20,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'D:/leetcode/wang-react-hooks/packages/hooks/src/useUnmountedRef/index.md?type=text'),
  },
  'components/useUpdateEffect/index': {
    frontmatter: fm21,
    toc: t21,
    demoIndex: dmi21,
    textGetter: () => import(/* webpackChunkName: "meta__packages" */'D:/leetcode/wang-react-hooks/packages/hooks/src/useUpdateEffect/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
