// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'D:/leetcode/wang-react-hooks/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.9_@types+node@22.13.5_eslint@8.57.1_jest@29.7.0_prettier@2.8.8_r_mri3hv5on3q6hiutw435uoveqi/node_modules/dumi/theme-default/builtins/Previewer/index.js';
